# Site settings
title: TelcoSec - Telecom Security
email: git@telco-sec.com
description: > # this means to ignore newlines until "baseurl:"
  Enhance your network's protection with TelcoSec, your trusted solution for cutting-edge Telecom Security. Safeguard your telecommunications infrastructure with advanced security measures tailored to the unique challenges of the telecom industry.
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://telco-sec.com" # the base hostname & protocol for your site
sitemap: true
#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: rfs

copyright:
   name: TelcoSec
   link: 'https://telco-sec.com/'

# Build settings
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker


# Comments
disqus: yes
disqus-shortname: poplab

#social
facebook: https://www.facebook.com/PopLabResearch
quora: http://quora.com/
twitter: http://twitter.com/
github: http://github.com/
email: your@email.com

#facebook like box
fb-like-box: yes
fb-app-id: xxxxxxxx
fb-page-url: https://www.facebook.com/PopLabResearch
fb-page-title: PopLabResearch

# Sass style
sass:
  style: compressed

# google News
publisher: "PopLab Agency"
# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-news-sitemap
  - jekyll-sitemap



social:
  name: TelcoSec
  links:
    - https://www.linkedin.com/showcase/telcosec


# Images

defaults:
  - scope:
      path: ""
    values:
      image: /images/cover.png


google:
  tag_manager:
    container_id: GTM-5DGDDTS8
analytics: G-SDPPC95R4J

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true 
  show_dark_mode_toggle_in_bottom: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode
  show_dark_mode_toggle_in_mobile_menu: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode


mailchimp:
  form_action_url: https://zerostatic.us13.list-manage.com/subscribe/post?u=675276692aebec1c007f8156d&amp;id=3e3da720c2
